### ISSUE TITLE
Ambient light sensor (ALS-PT19) examples.

### ISSUE THREAD

**Issue by Expecho** [Avnet/AvnetAzureSphereStarterKitReferenceDesign#4]
Can you include an example of how to read the built in ambient light sensor?

**Comment by Expecho** [comment]
I managed to get some thing working by using [this sample](https://github.com/Azure/azure-sphere-samples/tree/master/Samples/ADC) as a guide. I created a project based on this repo which includes reading values from the ADC controller. See the result [here](https://github.com/Expecho/IoT/tree/develop/AzureSphere/MySphere) but I have no idea on how to interpret the values. Currenly I do it like [this](https://github.com/Expecho/IoT/blob/develop/AzureSphere/MySphere/main.c#L413):

````c
float voltage = ((float)value * sampleMaxVoltage) / (float)((1 << sampleBitCount) - 1);
Log_Debug("ALS-PT19: Output [xxx] :  %6.6f V\n", voltage);
````

If I can get some help as to how to interpret the values given by the ALS-PT19 sensor I can finish it and maybe create a PR? The specsheet of the sensor can be found [here](http://www.everlight.com/file/ProductFile/201407061531031645.pdf) but since I have really no clue on how to connect the dots maybe someone can help?

The output I currently get is like

````
LSM6DSO: Acceleration [mg]  : 5.4900, -7.3200, 1010.5260
LSM6DSO: Angular rate [dps] : 0.00, 0.00, 0.00
LSM6DSO: Temperature  [degC]: 30.29
LPS22HH: Pressure     [hPa] : 1024.34
LPS22HH: Temperature  [degC]: 29.05
ALS-PT19: Output [xxx] :  0.259463 V
````

**Comment by PeterFenn** [comment]
Based on the **ADC_RTApp_MT3620_BareMetal** example that you reference, please review the "[Advanced Tutorial](http://avnet.me/azsphere-TUTORIAL)" blog on Element14 and it's [github repo](https://github.com/Avnet/Azure_Sphere_SK_ADC_RTApp). This reference design uses one of the M4 cores to periodically sample the ADC and report the voltage of the measured values. 
[http://avnet.me/azsphere-TUTORIAL](http://avnet.me/azsphere-TUTORIAL)

**Comment by PeterFenn** [comment]
PS: Conversion of the raw ADC values into Lux light intensity values gets done on line 273 of **[main.c](https://github.com/Avnet/Azure_Sphere_SK_ADC_RTApp/blob/master/AvnetAzureSphereSK_OLED/AvnetStarterKitReferenceDesign/main.c)** of the companion A7 application ([AvnetAzureSphereSK_OLED](https://github.com/Avnet/Azure_Sphere_SK_ADC_RTApp/tree/master/AvnetAzureSphereSK_OLED/AvnetStarterKitReferenceDesign)) 
// get voltage (2.5*adc_reading/4096)
// divide by 3650 (3.65 kohm) to get current (A)
// multiply by 1000000 to get uA
// divide by 0.1428 to get Lux (based on fluorescent light Fig. 1 datasheet)
// divide by 0.5 to get Lux (based on incandescent light Fig. 1 datasheet)
// We can simplify the factors, but for demostration purpose it's OK
light_sensor = ((float)analog_data.u32*2.5/4095)*1000000 / (3650*0.1428);

**Comment by Expecho** [comment]
Thanks, you are of great help!
